"""added language column to Posts model

Revision ID: 109c8ed06f5d
Revises: 566ccfe75e80
Create Date: 2019-07-11 22:10:44.827569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109c8ed06f5d'
down_revision = '566ccfe75e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
